#!/usr/bin/python

import os
import sys
import socket
import time
import beahlib
from beah.misc.jsonenv import json
from beah.core import event

if __name__ == '__main__':
    t = beahlib.get_task(sender=beahlib.SocketSender(nowait=True))
    t.linfo("task started...")
    t.ldebug("environment", environment=dict(os.environ))
    time.sleep(10)
    t.passed("pass1")
    time.sleep(10)
    t.warning("warn1")
    time.sleep(10)
    t.linfo("task finished...")
