#!/bin/bash

if [[ "$1" == "check" ]]; then
  dir=$(mktemp -d -t logs-XXXX)
  file=$dir.tar.gz
  mkdir $dir/var
  cp -R /var/beah $dir/var/
  mkdir $dir/tmp
  cp /tmp/beah* $dir/tmp/
  mkdir $dir/var/log
  cp /var/log/beah* $dir/var/log/
  grep ': ERROR ' $dir/var/log/beah* | grep -v ': DEBUG ' | beah-check cat-error
  cp -R /var/log/rhts $dir/var/log/
  tar cvf $file -C $(dirname $dir) $(basename $dir)
  rm -rf $dir
  beah-check cp $file logs.tar.gz
  rm -f $file
fi

