#!/bin/bash

if [[ "$1" == "check" ]]; then
  dir=$(mktemp --directory --tmpdir=/tmp logs-XXXX)
  file=$dir.tar.gz
  mkdir $dir/var
  cp -R /var/beah $dir/var/
  mkdir $dir/tmp
  cp /tmp/beah* $dir/tmp/
  mkdir $dir/var/log
  cp /var/log/beah* $dir/var/log/
  cp -R /var/log/rhts $dir/var/log/
  tar cvf $file $dir
  rm -rf $dir
  beah-check cp $file logs.tar.gz
  rm -f $file
fi

