#!/bin/bash

if [[ "$1" == "check" ]]; then
  free | beah-check cat --tee free.out
  df | beah-check cat --tee df.out
  top -b -n 1 | beah-check cat --tee top.out
  ps -elfH | beah-check cat --tee ps-elfH.out
fi

