#!/bin/bash
#
# beah-beaker-backend:	Start the Beaker backend.
#
# chkconfig:	- 99 99
# description:	Daemon linking Beaker Harness with Lab Controller.

# Source function library.
. /etc/rc.d/init.d/functions

# CUSTOMIZE THESE VARIABLES:

# NOTE: predefined functions (daemon, killproc, status) init.d/functions in
# el4 do not support -p/--pidfile options. pidfile has to be named same as
# binary file.
#
# In order to have multiple daemons of same type running at the same time it
# is necessary/recomended to create a wrapper with different name.
prog=beah-beaker-backend
# FIXME: path should use the prefix used during installation, not the const
# /usr
BEAH_INSTALL_ROOT=/usr
# FIXME: may need to change this(?)
RUN_AS=root

if [ -f /etc/profile.d/cobbler.sh ]; then
    . /etc/profile.d/cobbler.sh
fi

if [ -f /etc/sysconfig/$prog ]; then
    . /etc/sysconfig/$prog
fi

# DO NOT CHANGE THESE VARIABLES WITHOUT GOOD REASON:

path="$BEAH_INSTALL_ROOT/bin/$prog"
PIDFILE=/var/run/${prog}.pid
THELOCK=/var/beah/lock/$prog

start() {
    [ -f $path ] || exit 5
    if service NetworkManager status; then
        echo $"Waiting for network..."
        if [[ -x "/usr/bin/nm-online" ]]; then
            /usr/bin/nm-online
        fi
    else
        echo $"Network is not managed by NM."
    fi
    echo -n $"Starting $prog: "
    daemon --user $RUN_AS $path "$OPTIONS >> /tmp/$prog.out 2>&1 &" 'echo $!' ">$PIDFILE"
    RETVAL=$?
    echo
    echo "$prog running as process `cat $PIDFILE`"
    if test $RETVAL = 0; then
        mkdir -p $(dirname $THELOCK) &> /dev/null
        touch $THELOCK
    fi
    return $RETVAL
}

stop() {
    echo -n $"Stopping $prog: "
    if ! killproc $path; then
        kill `cat $PIDFILE`
    else
        true
    fi
    RETVAL=$?
    echo
    rm -f $THELOCK
    return $RETVAL
}

restart() {
    stop
    start
}

condrestart(){
	[ -e $THELOCK ] && restart
	return 0
}

# See how we were called.
case "$1" in
    start)
	start
	;;
    stop)
	stop
	;;
    status)
	status $prog
	RETVAL=$?
        ;;
    restart)
	restart
	;;
    condrestart|try-restart)
	condrestart
	;;
    reload)
        ;;
    force-reload)
        restart
        ;;
    usage|*)
	echo $"Usage: $0 {start|stop|status|restart|condrestart|reload|force-reload|usage}"
	;;
esac
exit $RETVAL
