#!/bin/bash
#
# beah-srv:	Start the Beaker Harness server
#
# chkconfig:	- 98 98
# description:	The Beaker Harness server. Backend is required too...

# Source function library.
. /etc/rc.d/init.d/functions

# CUSTOMIZE THESE VARIABLES:

# NOTE: predefined functions (daemon, killproc, status) init.d/functions in
# el4 do not support -p/--pidfile options. pidfile has to be named same as
# binary file.
#
# In order to have multiple daemons of same type running at the same time it
# is necessary/recomended to create a wrapper with different name.
prog=beah-srv
# FIXME: path should use the prefix used during installation, not the const
# /usr
BEAH_INSTALL_ROOT=/usr
# FIXME: may need to change this(?)
RUN_AS=root

if [ -f /etc/sysconfig/$prog ]; then
    . /etc/sysconfig/$prog
fi

# DO NOT CHANGE THESE VARIABLES WITHOUT GOOD REASON:

path="$BEAH_INSTALL_ROOT/bin/$prog"
PIDFILE=/var/run/${prog}.pid
LOCKFILE=/var/lock/subsys/$prog

start() {
    [ -f $path ] || exit 5
    # el3,4,5 do not clean subdirectories on boot. el6 and fedora do.
    # anything going to R/W into /var/run/beah should go through this!
    echo $"$prog: Waiting for lock."
    lockfile /var/run/beah.lock
      # remove files only if beah-rm.lock can be obtained:
      if lockfile -0 -r 0 /var/run/beah/rm.lock; then
        echo $"$prog: Performing /var/run/beah clean-up"
        find /var/run/beah ! -type d -exec rm -f {} \;
      fi
    rm -f /var/run/beah.lock
    echo -n $"Starting $prog: "
    daemon --user $RUN_AS $path "$OPTIONS >> /tmp/$prog.out 2>&1 &" 'echo $!' ">$PIDFILE"
    RETVAL=$?
    echo
    echo "$prog running as process `cat $PIDFILE`"
    if test $RETVAL = 0; then
        touch $LOCKFILE
    fi
    return $RETVAL
}

stop() {
    echo -n $"Stopping $prog: "
    if ! killproc $path; then
        kill `cat $PIDFILE`
    else
        true
    fi
    RETVAL=$?
    echo
    rm -f $LOCKFILE
    return $RETVAL
}

restart() {
    stop
    start
}

condrestart(){
	[ -e $LOCKFILE ] && restart
	return 0
}

# See how we were called.
case "$1" in
    start)
	start
	;;
    stop)
	stop
	;;
    status)
	status $prog
	RETVAL=$?
        ;;
    restart)
	restart
	;;
    condrestart|try-restart)
	condrestart
	;;
    reload)
        ;;
    force-reload)
        restart
        ;;
    usage|*)
	echo $"Usage: $0 {start|stop|status|restart|condrestart|reload|force-reload|usage}"
	;;
esac
exit $RETVAL
